version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    depends_on:
      - mongodb
    links:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
